# Generated by Django 2.1.2 on 2019-07-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.department'),
        ),
    ]
