# Generated by Django 2.1.2 on 2019-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='departments',
        ),
    ]
