# Generated by Django 2.1.2 on 2019-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190301_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Department',
            field=models.CharField(default='NULL', max_length=80),
        ),
    ]
