# Generated by Django 2.1.2 on 2019-03-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Photos',
            new_name='StaffID',
        ),
    ]
