# Generated by Django 2.1.2 on 2019-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190321_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='StaffID',
            field=models.CharField(default='JEC', max_length=100),
        ),
    ]
