# Generated by Django 2.1.2 on 2019-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20190321_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('Administration', 'Administration'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('ME', 'ME'), ('BSH', 'BSH')], max_length=80),
        ),
    ]
