# Generated by Django 2.1.2 on 2019-04-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190418_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='StaffID',
            new_name='jecc_code',
        ),
    ]
