# Generated by Django 2.1.2 on 2019-07-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
        ('contacts', '0014_departments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departments',
            new_name='department',
        ),
    ]
