# Generated by Django 2.1.2 on 2019-07-18 09:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0014_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], default='Select semester', max_length=80)),
                ('Time_Table_of_Division_A', models.FileField(help_text='If there is only one division please upload to here', upload_to='TimeTable/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Time_Table_of_Division_B', models.FileField(blank=True, default=None, help_text="Don't uploade anything if there  is no Division B ", null=True, upload_to='TimeTable/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.departments')),
            ],
        ),
    ]
