# Generated by Django 2.1.2 on 2019-07-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20190718_1531'),
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTable',
            new_name='TimeTables',
        ),
    ]
